apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: grafana-admin-credentials-sync
  namespace: monitoring
spec:
  vaultAuthRef: static-auth
  mount: secrets
  type: kv-v2
  path: monitoring-secrets
  destination:
    name: grafana-admin-credentials
    create: true
  refreshAfter: 5m # Changed from refreshInterval to refreshAfter