apiVersion: apps/v1
kind: Deployment
metadata:
  name: linker-backend
  namespace: devops-project
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: hammedbabatunde/devopsbootcamp-backend:1.10
        ports:
        - containerPort: 3001
        envFrom:
        - secretRef: { name: app-secrets }
        - configMapRef: { name: app-config }
        env:
        - name: DATABASE_URL
          value: "postgresql://$(DB_USER):$(DB_PASSWORD)@postgres-service:5432/linker_db?schema=public"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: devops-project
spec:
  selector:
    app: backend
  ports:
    - port: 80
      targetPort: 3001