apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: postgres-secrets-sync
  namespace: devops-project
spec:
  vaultAuthRef: static-auth
  mount: secret # Your KV secrets engine name
  type: kv-v2
  path: backend-secrets # The path where your DB_USER and DB_PASSWORD live
  
  # This is the "Magic" part: it creates the K8s secret automatically
  destination:
    name: app-secrets 
    create: true
  
  # How often to check for updates
  refreshInterval: 5m