server:
  standalone:
    enabled: true
    config: |
      ui = true

      listener "tcp" {
        tls_disable = 1
        address     = "[::]:8200"
        cluster_address = "[::]:8201"
      }

      storage "file" {
        path = "/vault/data"
      }

      # AWS KMS Auto-Unseal Configuration
      seal "awskms" {
        region     = "eu-north-1"
        kms_key_id = "arn:aws:kms:eu-north-1:088544772255:key/80f51de3-e04c-4e8e-b6ee-e0972aba2836"
      }

injector:
  enabled: true